### ISSUE TITLE
 PHP Fatal error:  Uncaught Error: Class 'Monolog\Logger' not found

### ISSUE THREAD

**Issue by MuhShalah007** [slimphp/Slim-Skeleton#103]
```
> php -S localhost:8080 -t public
[Sat Jun 22 06:23:31 2019] PHP Fatal error:  Uncaught Error: Class 'Monolog\Logger' not found in /mnt/g/AkademikApps/src/settings.php:16
Stack trace:
#0 /mnt/g/AkademikApps/public/index.php(17): require()
#1 {main}
  thrown in /mnt/g/AkademikApps/src/settings.php on line 16
[Sat Jun 22 06:23:31 2019] 127.0.0.1:63621 [500]: / - Uncaught Error: Class 'Monolog\Logger' not found in /mnt/g/AkademikApps/src/settings.php:16
Stack trace:
#0 /mnt/g/AkademikApps/public/index.php(17): require()
#1 {main}
  thrown in /mnt/g/AkademikApps/src/settings.php on line 16
```

**Comment by shadowhand** [comment]
Do you have `monolog/monolog` required in `composer.json` ?

**Comment by MuhShalah007** [comment]
> Do you have `monolog/monolog` required in `composer.json` ?

yes `{
    "name": "slim/slim-skeleton",
    "description": "A Slim Framework skeleton application for rapid development",
    "keywords": ["microframework", "rest", "router", "psr7"],
    "homepage": "http://github.com/slimphp/Slim-Skeleton",
    "license": "MIT",
    "authors": [
        {
            "name": "Josh Lockhart",
            "email": "info@joshlockhart.com",
            "homepage": "http://www.joshlockhart.com/"
        }
    ],
    "require": {
        "php": ">=5.6",
        "slim/slim": "^3.1",
        "slim/php-view": "^2.0",
        "monolog/monolog": "^1.17"
    },
    "require-dev": {
        "phpunit/phpunit": ">=5.0"
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "config": {
        "process-timeout": 0,
        "sort-packages": true
    },
    "scripts": {
        "start": "php -S localhost:8080 -t public",
        "test": "phpunit"
    }
}`

**Comment by l0gicgate** [comment]
Can you show your index.php? Php Version? Sounds like you aren’t loading the dependencies. Make sure you require `vendor/autoload.php`

**Comment by l0gicgate** [comment]
Feel free to re-open this issue. Closing for now since no feedback is being provided.

**Comment by bhuyInfinitalk279** [comment]
Make sure imported this code `require 'vendor/autoload.php';` that worked for me ^^

example index.php

> <?php
require 'vendor/autoload.php';

use Monolog\Level;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

$log = new Logger('bbb');

$log->pushHandler(new StreamHandler('aa.log', Level::Warning));

// $log->pushHandler(new StreamHandler('php://stdout', Level::Warning));

$log->warning('Foo');
$log->error('Bar');
