### ISSUE TITLE
New slim-skeleton not working on nginx getting 403 message

### ISSUE THREAD

**Issue by learnme2019** [slimphp/Slim-Skeleton#106]
Hi I just created a new project with composer   composer create-project slim/slim-skeleton
and in my nginx.conf I have this settings.
location ~ ^/slim-skeleton{
          try_files $uri $uri/ /slim-skeleton/public/index.php$is_args$args;
        }
but my output I get as this 

<html>

<head>
	<title>403 Forbidden</title>
</head>

<body>
	<center>
		<h1>403 Forbidden</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>

**Comment by l0gicgate** [comment]
This seems like a configuration issue with Nginx. Please show logs and configuration file.

**Comment by l0gicgate** [comment]
I'm closing this as resolved, feel free to re-open with more insights.

**Comment by learnme2019** [comment]
Hi,
       Which logs will you prefer then I post it here?

**Comment by l0gicgate** [comment]
Any logs. From either Nginx or PHP

**Comment by brutto** [comment]
@learnme2019 Are you sure that you install project into the root folder `/slim-skeleton/public/index.php`?

**Comment by l0gicgate** [comment]
I'm closing this as no further user feedback has been provided
