### ISSUE TITLE
Duplicate app creation code

### ISSUE THREAD

**Issue by ssnepenthe** [slimphp/Slim-Skeleton#111]
The code used to create the app instance is duplicated in `public/index.php` and `tests/TestCase.php`.

What would you think about moving this logic to a dedicated file (e.g. `app/bootstrap.php`) which would return the app instance?

Wherever the app is needed you can now just do:

```php
$app = require __DIR__ . '/../app/bootstrap.php';
```

**Comment by l0gicgate** [comment]
That's assuming that the app needs to be instantiated exactly the same as in the `bootstrap.php` file within the test case over its lifetime. Hence why the code is duplicated.
