### ISSUE TITLE
Consider taking advantage of PHP-DI container compilation

### ISSUE THREAD

**Issue by ssnepenthe** [slimphp/Slim-Skeleton#112]
According to the [PHP-DI docs](http://php-di.org/doc/php-definitions.html#setting-definitions-in-the-container-directly), setting definitions in the container directly via the `set` method prevents entries from being added to a compiled container.

Would you have any objections to reworking the container creation logic in order to:

1. Use the `DI\ContainerBuilder` class
2. Conditionally enable compilation based on some environment setting
3. Use array definitions instead of directly setting items on the container

**Comment by ssnepenthe** [comment]
Just for an idea of what this might look like:

https://github.com/ssnepenthe/Slim-Skeleton/commit/08981c32e451f839ecbe1fe7ee8f74f695fe3444

**Comment by l0gicgate** [comment]
Definitely open to doing so. Would you like to raise a PR for it?
