### ISSUE TITLE
Docker under win10

### ISSUE THREAD

**Issue by huncyrus** [slimphp/Slim-Skeleton#118]
Hi, 

I just started a skeleton based project. Tried to use the docker (via win10 + docker-tools). I made the call of `docker-compose up -d`
I do expected a start, but nothing hapened. So I just called a `docker-compose up` and got the following error message: 

> starting myslim4test_slim_1 ... done
> Attaching to myslim4test_slim1
> slim_1 | Directory public does not exists.
> myslim4test_slim_1 exited with code 1

And my structure is like the basic, so I do have a `public` folder. I did not changed anything. Any idea what could be wrong? 
Then I copied all the files into a virtualbox (ubuntu, latest, php 7.3). And just hitted the `compose start` command, and it working well. 
Then I tried with docker, same result. 

All permission is properly set (755 for dirs, 644 for files). Full permission under windows (since no other option there...).

Cheers

**Comment by l0gicgate** [comment]
I'll have to verify this on the 4.x branch and update the docker-compose file I assume, it was picked up from 3.x and I never tested it.

**Comment by l0gicgate** [comment]
I tested with `docker-compose up -d` and navigated to `localhost:8080` and I get `Hello World!` so the config that's present here works. Closing this as resolved.
