### ISSUE TITLE
Getting 404 all the time

### ISSUE THREAD

**Issue by lakinmohapatra** [slimphp/Slim-Skeleton#120]
Hi installed latest slim skeleton. But routes are not working at all. Always sending 404 errors .

**Comment by l0gicgate** [comment]
That’s most likely your web server configuration. 

Are you running Apache?

Are you running the app in a sub-directory?

**Comment by odan** [comment]
There is no route for `/`. 

There is only a route for `users` and `users/{id}`. This is frustrating for many newcomers.

Could we please add a route for `/` to make it easier for new users?

https://github.com/slimphp/Slim-Skeleton/blob/master/app/routes.php#L12

**Comment by odan** [comment]
Another issue is that there is no official solution for running Slim 4 with Apache. Running Slim 4 under a sub-directory is an additional problem.

I think we should add at least the missing `.htaccess` files to this skeleton and a working solution for Apache.

There is only a workaround to fix the `REQUEST_URI` before the App is created.

```php
// ...

// Fix apache base path.
// Change the request uri to run the app in a subdirectory.
call_user_func(static function () {
    $path = parse_url($_SERVER['REQUEST_URI'])['path'];
    $scriptName = dirname(dirname($_SERVER['SCRIPT_NAME']));
    $len = strlen($scriptName);
    if ($len > 0 && $scriptName !== '/') {
        $path = substr($path, $len);
    }
    $_SERVER['REQUEST_URI'] = $path ?: '';
});

$app = AppFactory::create();

// ...
```

Is there a better solution?
