### ISSUE TITLE
slim/psr7: dev-master

### ISSUE THREAD

**Issue by lightswitch05** [slimphp/Slim-Skeleton#121]
Any insights why `slim/psr7` needs to be set at `dev-master`?

It looks like the latest tag is `0.4.0`. Which has the last commit from August 2nd: https://github.com/slimphp/Slim-Psr7/commit/d312896b7cd4aca7d4b86b64acdfcb5cc3da758f

There have been 22 commits on the master branch since tag `0.4.0`. I assume there is _something_ in those 22 commits that is needed but hasn't been released yet?

However, `slim/psr7:dev-master` was set on April 23rd in commit https://github.com/slimphp/Slim-Skeleton/commit/83c9c9a0cba2c7356e326410f3a9ea86851098a6#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 

So, since it was set to `slim/psr7:dev-master` on April 23rd - there has been tagged releases, the latest being 14 days ago. So it goes to reason, there is nothing in those last 22 commits that was needed when the version was originally set to dev-master. Perhaps `dev-master` isn't needed anymore and it should be set to the latest version, `0.4.0`?

Any insights are appreciated. Thanks!

**Comment by l0gicgate** [comment]
I will be tagging a new release for Slim-Psr7 soon, once that's done. We will change it to `^0.5` once that's done.

**Comment by lightswitch05** [comment]
Great, thank you @l0gicgate !
