### ISSUE TITLE
Missing call to ``ob_clean`` in Advanced Shutdown Handler

### ISSUE THREAD

**Issue by raffster-dev** [slimphp/Slim-Skeleton#134]
In [Advanced Shutdown Handler](http://www.slimframework.com/docs/v4/objects/application.html#notices-and-warnings-handling) section of the documentation is shown a call to ``ob_clean`` so the default error message is cleared before the new response is emitted.

This skelleton is missing the call to ``ob_clean``.

**Comment by l0gicgate** [comment]
Fixed via #135
