### ISSUE TITLE
PDO

### ISSUE THREAD

**Issue by flahol** [slimphp/Slim-Skeleton#139]
Most of the time we need to connect to a database.
Could we have a setup for example for 2 PDO database connections ?

In **setting.php** something like :
```
 'db' => [
                'host' => 'xxx'
                'dbname' => 'db',
                'username' => 'user',
                'password' => 'password',
                'options' => ['charset' => 'utf8'],
            ],
 'db2' => [
                'host' => 'xxx'
                'dbname' => 'db2',
                'username' => 'user2',
                'password' => 'password2',
                'options' => ['charset' => 'utf8'],
            ],
```
and some code in dependencies.php or external file db.php
and then update the index.php
and include some repository example how to use db and db2

**Comment by farukgaric** [comment]
https://stackoverflow.com/questions/57758020/how-to-set-up-and-inject-multiple-pdo-database-connections-in-slim-4/57758106#57758106
