### ISSUE TITLE
OPTIONS request before GET request with Authorization Header not working

### ISSUE THREAD

**Issue by ankur2194** [slimphp/Slim-Skeleton#140]
I have cloned this skeleton which already have CORS implemented.
But still when API calls OPTIONS before GET, it sends 405 ERROR "Method not allowed. Must be one of: GET"

Here is my route where I face this error. `$group->get('/users', ListUsersAction::class);`

```
    $app->group('', function (Group $group) {
        $group->post('/user/create', CreateUsersAction::class);
        $group->get('/users', ListUsersAction::class);
        $group->get('/user/{id}', ViewUserAction::class);
    })->add(AuthenticationMiddleware::class);
```

The same route is working from postman. And same route is working if I remove Authorization token from header. 
Execution does not even reach to first line of "AuthenticationMiddleware".

However I tested it by adding same option route without "AuthenticationMiddleware".
like this:
```
    $app->options('/users', function(Request $request, Response $response) {return $response;});

    $app->group('', function (Group $group) {
        $group->post('/user/create', CreateUsersAction::class);
        $group->get('/users', ListUsersAction::class);
        $group->get('/user/{id}', ViewUserAction::class);
    })->add(AuthenticationMiddleware::class);
```

This is working. So I guess I forgot to add some code or I did any miskate which causing the error, or the skeleton has a bug.

Can anyone help on this?
Thanks in advance.

**Comment by l0gicgate** [comment]
That’s because you need to add CORS route handling to the routes.php file. 

```php
$app->options('/{routes:.+}', function ($request, $response, $args) {
    return $response;
});
```

**Comment by ankur2194** [comment]
Hell @l0gicgate,

Thankyou very much for the reply.
Yes your solutin worked. - Working Now.

Also when I added `options` route for `/users`, it was working, like I mentioned below code block.
But I wasn't sure if that is the right way to make it working, b'cos I thought I was just using a patch to solve the problem.

So yes better option is to use a wildcard route of `option` method.
But is this the right way to solve it? Or this is still a patch?

Thank you very much for reply and helping with the issue.

**Comment by l0gicgate** [comment]
@ankur2194 it's not a patch. It's the default way of handling the `OPTIONS` pre-flight request as seen in the documentation:
http://www.slimframework.com/docs/v4/cookbook/enable-cors.html

We should definitely add that to the skeleton though. I'll make a PR.

**Comment by vhsanga** [comment]
Maybe this can help you

https://stackoverflow.com/questions/60274846/slim-framework-throws-405-not-found-error-on-every-request/69916314#69916314
