### ISSUE TITLE
Middleware doesn't work

### ISSUE THREAD

**Issue by bautrukevich** [slimphp/Slim-Skeleton#147]
I am trying to add any middleware, as example http://www.slimframework.com/docs/v4/cookbook/route-patterns.html

```php
<?php
declare(strict_types=1);

use App\Application\Middleware\SessionMiddleware;
use Middlewares\TrailingSlash;
use Slim\App;

return function (App $app) {
    $app->add(SessionMiddleware::class);
    $app->add(new TrailingSlash(true)); // true adds the trailing slash (false removes it)
};
```

But this doesn't work and I don't understand. Why? Can you help, please?

**Comment by aj-nk** [comment]
Same here. I tried to use the doc's code to write my own middleware.
```
<?php
declare(strict_types=1);

use App\Application\Middleware\NoTrailingSlashMiddleware;
use App\Application\Middleware\SessionMiddleware;
use Slim\App;

return function (App $app) {
    $app->add(SessionMiddleware::class);
    $app->add(NoTrailingSlashMiddleware::class);
};
```
If the route exists, both middlewares are executed (no slash needs to be removed), so everything works fine. But if I add a `/` to the route, none of them are executed and I'm always getting
```
{
    "statusCode": 404,
    "error": {
        "type": "RESOURCE_NOT_FOUND",
        "description": "Not found."
     }
}
```
as a result. I did not have a closer look at the code so far, but it seems to me that any middleware is executed only if the route is valid. A middleware to remove the trailing slash should usually transform an non-existing path, so it needs to be executed before checking the route. Just a guess on my part.

**Comment by alturic** [comment]
Might be a silly question, but are you defining middleware before or after the error handler?

**Comment by aj-nk** [comment]
> Might be a silly question, but are you defining middleware before or after the error handler?

Except the single line in the `app/middleware.php` file, I did not make any changes in the code. So looking at the `public/index.php` file, middlewares are registered before the error handler.

**Comment by l0gicgate** [comment]
The `NoTrailingSlashMiddleware` should be added after the routing middleware so it executes before routing is done.

**Comment by Moritz-Fortmann** [comment]
As @l0gicgate pointed out you need to add the TrailingSlash Middleware after the Routing Middleware is added. Since Slim operates after the **LIFO** (Last in first out) principle. Otherwise the Routing Middleware will be executed before the changes of the TrailingSlash Middleware would be applied.

//index.php
$app->addRoutingMiddleware();
$app->addMiddleware(new Middlewares\TrailingSlash(true));

:)

**Comment by l0gicgate** [comment]
I'm marking this as resolved.
