### ISSUE TITLE
Too Complex Starting Point

### ISSUE THREAD

**Issue by nixoncode** [slimphp/Slim-Skeleton#150]
Looks like the starting point for slim application has become complex recently,

When someone does `composer create-project`, I have to delete a lot of files and folders before starting on development.

can it be simplified to the minimum bare bones, as it is for 2.x

**Comment by maurobonfietti** [comment]
Hi, I found this and maybe it's useful for you too:

```bash
$ composer create-project akrabat/slim4-empty my-new-project
```

Check it out:

https://akrabat.com/slim4-empty-minimal-slim-4-starting-point/

**Comment by ideaguy3d** [comment]
I ABSOLUTELY agree!!!!!!!!! It is utterly infuriating how God Damned **complex it is to JUST get up and running**. I've spent the past 5+ hours studying Apache documentation to figure out what a "Virtual Host Document Root" is and how to set it from my web host, and still haven't figured it out 😠 

I already have to memorize  

- thousands of configs for my jobs' IIS server, SQL Server, and internal systems, 
- an overwhelming amount of functions in PHP, Node.js, T-SQL, Excel, xBase, PowerShell, 
- the never ending amount of frameworks/libraries/modules/extensions in each language, 
- and now I have to learn how to set the document root from a virtual host to use the slim4 skeleton... like WTF?!? 

My human brain is just a balloon that's about to explode!!! But to anyone else who may be feeling my frustration, here is the pertinent docs (but I can't help you with your web host/cloud vendor)

- [Directive Dictionary](http://httpd.apache.org/docs/current/mod/directive-dict.html#Syntax)
- [REQUEST_FILENAME](http://httpd.apache.org/docs/current/expr.html#vars)
- [Virtual Host](http://httpd.apache.org/docs/current/mod/core.html#virtualhost)
- [RewriteRule directive](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriterule)
- [RewriteBase directive, RewriteCond is right below it](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritebase)
- [DocumentRoot](http://httpd.apache.org/docs/2.4/mod/core.html#documentroot)

... It's a good thing reading for HOUR AND HOURS on end is a TON of fun! Good luck fellow PHP programmers who aren't that familiar with the underlying Apache .htaccess & httpd.conf stuff

**Comment by l0gicgate** [comment]
@adriansuter also has an excellent skeleton located here:
https://github.com/adriansuter/Slim4-Skeleton
