### ISSUE TITLE
Missing dependency.php due to update?

### ISSUE THREAD

**Issue by bvrulez** [slimphp/Slim-Skeleton#157]
I am doing this short tutorial to get to know slim: https://dev.to/charliedevelops/getting-started-with-slim-php-framework-by-building-a-very-simple-mvcoop-app-4j2b

Step 11 requires me to edit `src/dependency.php` (I guess he just misspelled the "a"). 

This file is not in the source code of slim-skeleton any more. Can you shortly explain why? Thanks!

**Comment by l0gicgate** [comment]
The file is called `dependencies.php` not `dependency.php`

**Comment by bvrulez** [comment]
I am sorry for the typo. The problem also was that `dependencies.php` now is in `app` (instead of in `src` as the tutorial suggests). Thanks for replying!
