### ISSUE TITLE
There was no release for some time

### ISSUE THREAD

**Issue by maciekpaprocki** [slimphp/Slim-Skeleton#159]
I was a bit surprised when I run create-project and it installed pretty old dependencies. 

It seems that this repo is using a lot of newer version, however, they are not released to packagist.

Two solutions that could help with maintaining that:

1. Doc using `composer create-project slim/slim-skeleton:dev-master slim` to setup skeleton. 
2. Dependabot could help you with creating automatic pull requests on dependencies update.  

I am happy to send PR to doc if you think that's right.

**Comment by l0gicgate** [comment]
I think that integrating dependabot on all our repos would probably be a great idea. Manually maintaining all these repos is very tedious. I wonder if we could also automate most of the release process. What do you think @adriansuter ?

**Comment by adriansuter** [comment]
Yes, I have never personally used dependabot, but it seems to be the right choice.

**Comment by l0gicgate** [comment]
A quick update on this, I just added dependabot to these repos:
- Slim
- Slim-Console
- Slim-Csrf
- Slim-Http
- Slim-Psr7
- Slim-Skeleton
- Slim-Website
- Twig-View

**Comment by maciekpaprocki** [comment]
Great for dependabot! It might give you loads of notifications, but in general, it's super easy to then update everything. 

When it comes to docs, I would still recommend the dev-master. It's not production used ( I cannot think how someone would want boilerplate to be used in prod ) so it's not really a problem, where people using old dependencies might be when it later goes to production.

**Comment by l0gicgate** [comment]
@maciekpaprocki in the midst of dealing with everything. I understand we have a lot of catching up to do haha.

> When it comes to docs, I would still recommend the dev-master
We should definitely do that so you're always up to date when creating the skeleton

**Comment by maciekpaprocki** [comment]
Send you PR for that. 

Thanks and you are doing an amazing job.

**Comment by l0gicgate** [comment]
I just did a release also! I’m closing this as resolved.
