### ISSUE TITLE
autoload location

### ISSUE THREAD

**Issue by jmslapa** [slimphp/Slim-Skeleton#175]
require(): Failed opening required '/home/jmslapa/projetos/slim-api/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/jmslapa/projetos/slim-api/public/index.php on line 11

Where is vendor folder?

**Comment by jmslapa** [comment]
using dump-autoload the folder vendor was created

**Comment by l0gicgate** [comment]
This is automatically done when you install dependencies via `composer install`
