### ISSUE TITLE
"ERROR: Module 'sqlite3' already loaded on line 0 in file Unknown.

### ISSUE THREAD

**Issue by subspider** [slimphp/Slim-Skeleton#185]
If i have this added in my server 
register_shutdown_function($shutdownHandler); 
I get this error.

```
{
    "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: Module 'sqlite3' already loaded on line 0 in file Unknown."
    }
}
```

Do you guys know or any clue how to fix it I don't see any code using sqlite so for me is a bit confusing why is loading such a module.

**Comment by l0gicgate** [comment]
Can you provide a small code sample? This is obviously a project specific issue and nothing to do with Slim-Skeleton. 

Please show your `index.php` along with any other dependencies you’ve declared yourself in app files. 

Thanks

**Comment by subspider** [comment]
It looks like it is server related I will close this somehow the server is the one loading this module 2 times the project I was using is this one so nothing new basically I grabbed this project and pleace it in my server.
