### ISSUE TITLE
 Install of phpstan/extension-installer failed

### ISSUE THREAD

**Issue by notRuslan** [slimphp/Slim-Skeleton#215]
Hello I tried to install by command : 
docker-compose run --rm api-php-cli composer create-project slim/slim-skeleton slim

And got error : 
 Install of phpstan/extension-installer failed
 [UnexpectedValueException]
  RecursiveDirectoryIterator::__construct(/app/slim/vendor/phpstan/extension-installer/.github): failed to open dir: Operation not permitted
As you can see I run it in Docker, ll file permissions is 777

**Comment by l0gicgate** [comment]
I'm closing this as stale.
