### ISSUE TITLE
Middleware on response not working on exception throw. Any possible solution?

### ISSUE THREAD

**Issue by daler445** [slimphp/Slim-Skeleton#229]
Hello!

None of any requests with thrown errors (exceptions) goes through middlewares, as it falls into registered_shutdown_function which declared in public/index.php: https://github.com/slimphp/Slim-Skeleton/blob/768b003e269cd6ce21681a47fdcfc5661288cadd/public/index.php#L66

In my project, I have middleware which logs every request and response:
```php
public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
{
	$this->logger->info('<-- Incoming request to "' . $request->getUri()->getPath() . '" (query: ' . $request->getUri()->getQuery() . ', body: ' . file_get_contents('php://input') . ', parsed body: '.var_export($request->getParsedBody(), true).'), headers: ' . var_export($request->getHeaders(), true));
	$response = $handler->handle($request);
	$this->logger->info('--> Response (#'.$response->getStatusCode().'): ' . $response->getBody() . ', headers: ' . var_export($response->getHeaders(), true));
	return $response;
}
```
And the problem is: from any action file, e.g. `src/Application/Actions/User/ListUsersAction.php`, I throw `HttpException`, but it does not go through any defined middlewares, but goes straight into registered shutdown function and request does not log. 

I know, I can log requests in shutdown_handler class, but it will duplicate code. And this solution will not work good for other middlewares – encrypting, signing, etc. 

Can you, please, suggest how can I solve this with a better way? 
Is there any way to attach middleware inside the shutdown handler?

**Below, code that executes now:**

Here how it works on exception throwing:
![](https://user-images.githubusercontent.com/29509446/121781881-3fd4c480-cbc0-11eb-8af4-b0e7cd7a665e.png)

How it works when no exceptions thrown:
![](https://user-images.githubusercontent.com/29509446/121782045-2122fd80-cbc1-11eb-8c3c-5352a0c2a01c.png)

This is how exceptions are thrown:
![](https://user-images.githubusercontent.com/29509446/121781934-888c7d80-cbc0-11eb-9657-ef68e55ef477.png)

Big thanks!

**Comment by eugene-borovov** [comment]
- Catch domain exception
- Add exception to request attribute
- Pass the request through all middlewares
- Rethrow exception from request attribute at the end (last middleware)

The main idea is not to use throwing exceptions to control the flow of the application.
