### ISSUE TITLE
Example for beginners on how to call vars from $this when looking at values from settings.php

### ISSUE THREAD

**Issue by Guyverix** [slimphp/Slim-Skeleton#248]
Running into issue calling values that are stored in the $this object..

The how-to for configuring the database connections was followed from:
https://arjunphp.com/how-to-connect-to-mysql-database-in-slim-framework-4/

If I follow the example exactly, it works within the route.php. 

However I am attempting to call the PDO class information stored inside $this down in the Actions and running into trouble.  I see that the $this object contains the values using "get_object_vars", however I cannot figure out how to call $this correctly to retrieve the values.

```
$test = $this->get(PDO::class);
returns:
"Call to undefined method…\NewPollerAction::get()"
```
In the dump it LOOKS like I should be able to get those values (I think)
```
-- logger stuff removed for clarity --
 [db] => Array ( [driver] => mysql [host] => 192.168.15.250 [username] => randouser [database] => event [password] => XXXX [charset] => utf8mb4 [collation] => utf8mb4_unicode_ci [flags] => Array ( [12] => [3] => 2 [20] => 1 [19] => 2 ) ) ) )
```
I would have guessed this would work, but does not:
$this->db, and I would have expected an array return back with all my db values

So my question is, how the heck do I use $this and retrieve what I need out of it correctly?  I figure if I can see it, I should be able to grab it AFAIK.  Google shows me really simple examples, but with all the added use statements, it is messy in my object and cannot figure out what I need to be calling as far as $this->???->db, or $this->???->(however many levels down it is)->db

I have autowire set in my use statement but it does not like the get() even with autowire in place, so I am a confused n00b.. :)

**Comment by Guyverix** [comment]
I should clarify, the "$test = $this->get(PDO::class);" is one of the attempts I have made in my Action however since I already see the data inside the object, I moved on to trying to pull it out via the "$this->???" logic.

Sorry for any confusion.

**Comment by l0gicgate** [comment]
You need to add `PDO::class` as a dependency in the constructor of your actions, PHP-DI will inject the dependency in there for you.

```php
<?php
declare(strict_types=1);

namespace App\Application\Actions\User;

use App\Application\Actions\Action;
use App\Domain\User\UserRepository;
use Psr\Log\LoggerInterface;

abstract class MyAction extends Action
{
    protected PDO $db;

    public function __construct(LoggerInterface $logger, PDO $db) {
        parent::__construct($logger);
        $this->db = $db;
    }

   protected function action(): Response
    {
        $test = $this->db->doSomething();
    }
}
```

**Comment by Guyverix** [comment]
Still getting errs that it cannot seem to find the PDO that was defined in the settings.php..
```
"Error while injecting dependencies into App\\Application\\Actions\\Mapping\\ViewAllMappingAction: No entry or class found for 'App\\Application\\Actions\\Mapping\\PDO'"
```

**Comment by Guyverix** [comment]
This is literally what I have defined in the depnedencies.php.  I know full well I am the one causing the problem not understanding the framework well enough yet.  Just one heck of a road-block that I cannot seem to get past.

```                                                                                          
<?php
declare(strict_types=1);

use App\Application\Settings\SettingsInterface;
use App\Application\Settings\Settings;
use DI\ContainerBuilder;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use Monolog\Processor\UidProcessor;
use Psr\Container\ContainerInterface;
use Psr\Log\LoggerInterface;

return function (ContainerBuilder $containerBuilder) {
    $containerBuilder->addDefinitions([
        LoggerInterface::class => function (ContainerInterface $c) {
            $settings = $c->get(SettingsInterface::class);

            $loggerSettings = $settings->get('logger');
            $logger = new Logger($loggerSettings['name']);

            $processor = new UidProcessor();
            $logger->pushProcessor($processor);

            $handler = new StreamHandler($loggerSettings['path'], $loggerSettings['level']);
            $logger->pushHandler($handler);

            return $logger;
        },
        PDO::class => function (ContainerInterface $c) {
            $settings = $c->get(SettingsInterface::class);
            $dbSettings = $settings->get('db');
            $host = $dbSettings['host'];
            $dbname = $dbSettings['database'];
            $username = $dbSettings['username'];
            $password = $dbSettings['password'];
            $charset = $dbSettings['charset'];
            $flags = $dbSettings['flags'];
            $dsn = "mysql:host=$host;dbname=$dbname;charset=$charset";
            return new PDO($dsn, $username, $password);
        },
    ]);
};
```

**Comment by eugene-borovov** [comment]
> Still getting errs that it cannot seem to find the PDO that are defined in the settings.php and dependencies.php files..
> 
> ```
> "Error while injecting dependencies into App\\Application\\Actions\\Mapping\\ViewAllMappingAction: No entry or class found for 'App\\Application\\Actions\\Mapping\\PDO'"
> ```

Add a backslash to the PDO class reference:

```php
abstract class MyAction extends Action
{
    protected \PDO $db;
```

**Comment by Guyverix** [comment]
No change.  Still says it cannot find the class.  In this framework, is it more reasonable to create a separate PDO file and call it with use instead of trying to make dependencies.php work?
```
Error while injecting dependencies into App\\Application\\Actions\\Mapping\\ViewAllMappingAction: No entry or class found for 'App\\Application\\Actions\\Mapping\\PDO'
```

**Comment by eugene-borovov** [comment]
```php
<?php
declare(strict_types=1);

namespace App\Application\Actions\User;

use App\Application\Actions\Action;
use App\Domain\User\UserRepository;
use Psr\Log\LoggerInterface;

abstract class MyAction extends Action
{
    protected \PDO $db;

    public function __construct(LoggerInterface $logger, \PDO $db)
    {
        parent::__construct($logger);
        $this->db = $db;
    }

   protected function action(): Response
   {
       $test = $this->db->doSomething();
   }
}
```

You`ve declared  the `\App\Application\Actions\Mapping`. So PDO without namespace will be `\App\Application\Actions\Mapping\PDO`. You need `\PDO` class for `$db` variable.

**Comment by Guyverix** [comment]
Thank you for the example.  This is making more sense to me now.
