### ISSUE TITLE
No access to apache configuration file

### ISSUE THREAD

**Issue by babeuloula** [slimphp/Slim-Skeleton#25]
Hello, 

I don't have access to the apache configuration file and my website is like this : http://www.mysite/public/

How I can remove the `public` folder from the URL ?
What should I write on my htaccess ?

Thanks

**Comment by akrabat** [comment]
Put your index.php file in your web root directory.

**Comment by babeuloula** [comment]
Ok but I need to disable the access to logs, src and templates folders.
There is no other way ?

**Comment by akrabat** [comment]
Use a host that allows you to to configure your web server?

**Comment by babeuloula** [comment]
I don't have any way to configure the server. Only a FTP access

**Comment by geggleto** [comment]
@babeuloula This is not a slim problem. Like @akrabat said get a host that will let you configure your environment.
