### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by webserveis** [slimphp/Slim-Skeleton#250]
{
    "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: Return type of App\\Application\\Actions\\ActionPayload::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice on line 67 in file C:\\xampp\\htdocs\\oneliners\\src\\Application\\Actions\\ActionPayload.php."
    }
}

**Comment by l0gicgate** [comment]
What version of PHP are you running?

**Comment by webserveis** [comment]
I test in XAMPP
PHP Version 8.1.1
