### ISSUE TITLE
Can not access static files with query string (the `?`)

### ISSUE THREAD

**Issue by picasso250** [slimphp/Slim-Skeleton#29]
The static file's URL is like `http://localhost:8080/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0`
And It report a 404.

It is because the `is_file()` called in line 5 of `index.php` regard file with `?v=4.4.0` as a different file path, so this function yields `false`.

I found 2 ways to fix it.

1. change the line 5 of `index.php` to `    $file = __DIR__ . explode('?', $_SERVER['REQUEST_URI'])[0];`
2. start server without router script like `php -S 0.0.0.0:8080 -t public`

**Comment by akrabat** [comment]
Fixed with #34
