### ISSUE TITLE
Why PHP-View?

### ISSUE THREAD

**Issue by abr4xas** [slimphp/Slim-Skeleton#31]
> PHP-View has no built-in mitigation from XSS attacks 
[source](https://github.com/slimphp/PHP-View#cross-site-scripting-xss-risks)

Why PHP-View instead Twig?

**Comment by tuupola** [comment]
You could also ask why use Slim instead of Silex or why use PHP instead of Ruby? Use whatever tool you like the most.

**Comment by abr4xas** [comment]
That's not the answer I was expecting. But you're right, I can use any other tool.

**Comment by tuupola** [comment]
If you are looking for native PHP templates check [Plates](http://platesphp.com/). It is pretty awesome.

**Comment by geggleto** [comment]
honestly its just the easiest migration tool for users coming from slim 2.

Plates and Twig are recommended, but for newer users/programmers php-view is just fine.
