### ISSUE TITLE
slim skeleton app file structure differs from repository when installed with composer

### ISSUE THREAD

**Issue by mob100** [slimphp/Slim-Skeleton#32]
hello, i developed a rest api about a month ago, now im trying to set a production enviroment but when i install the skeleton, i get a different file structure from any previous install, the src folder is gone and theres just the public folder available with all the skeleton code inside the index.php file, is there a way i can install the older one, wich includes src folder, i dont want to mess the file order i previously had with older file structure.

thanks.

**Comment by akrabat** [comment]
How did you install the skeleton?

**Comment by mob100** [comment]
composer create-project slim/slim-skeleton app-name over ssh

**Comment by akrabat** [comment]
That's not happening for me when I do:

    $ composer create-project slim/slim-skeleton app-name

I get this:

```
$ ls -l app-name/
total 56
-rw-rw-r--   1 rob  staff    583  6 Jun 06:06 CONTRIBUTING.md
-rw-rw-r--   1 rob  staff    842  6 Jun 06:06 README.md
-rw-rw-r--   1 rob  staff    589  6 Jun 06:06 composer.json
-rw-rw-r--   1 rob  staff  15032 29 Jun 15:11 composer.lock
drwxrwxr-x   3 rob  staff    102  6 Jun 06:06 logs
drwxrwxr-x   4 rob  staff    136  6 Jun 06:06 public
drwxrwxr-x   6 rob  staff    204  6 Jun 06:06 src
drwxrwxr-x   3 rob  staff    102  6 Jun 06:06 templates
drwxrwxr-x  10 rob  staff    340 29 Jun 15:11 vendor
```

**Comment by mumbaip** [comment]
I am also unable to see the src/ directory on centos.

[root@Vamsi composer]# 
[root@Vamsi composer]# cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

[root@Vamsi composer]# php composer.phar create-project slim/slim-skeleton myapp
Installing slim/slim-skeleton (2.1.2)
  - Installing slim/slim-skeleton (2.1.2)
    Loading from cache

Created project in myapp
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing monolog/monolog (1.20.0)
    Loading from cache

  - Installing slim/slim (2.6.2)
    Loading from cache

  - Installing slim/views (0.1.3)
    Loading from cache

  - Installing twig/twig (v1.24.1)
    Loading from cache

monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)
slim/views suggests installing smarty/smarty (Smarty templating system)
Writing lock file
Generating autoload files
[root@Vamsi composer]# ls myapp/
composer.json  composer.lock  logs  public  README.md  templates  vendor

**Comment by johnutzm** [comment]
Hi @mumbaip ,
Great idea to mention:

> CentOS release 6.6

and 

> Installing slim/slim-skeleton (2.1.2)

Looks like you don't get the 3.* version of the skeleton because it requires `php: >=5.5.0`. I bet you still have php 5.3.

**Comment by akrabat** [comment]
PHP 5.5. required for Slim 3.
