### ISSUE TITLE
How to update the skeleton with changes from this repo...

### ISSUE THREAD

**Issue by Guyverix** [slimphp/Slim-Skeleton#330]
Sorry to have to create an issue request due to my ignorance, but I need an assist.  Originally I followed the installation docs to get the skeleton in place, and everything is working as designed.  However since that time, there have been new releases here, and I am unable to figure out how to get the updated skeleton into my system.  

My main concern is that I do not want to clobber my existing code changes with the updates.

Would the best solution be start from scratch with a new skeleton install and copy my code over?

**Comment by WiGeeky** [comment]
@Guyverix I found your post at random but I hope my answer will be helpful to you. The intent of this project (and composer [create-project](https://getcomposer.org/doc/03-cli.md#create-project)) is to bootstrap/setup a new project that you're starting from scratch. so there isn't a standard way of doing what you want to do.

 Is there any particular reason/addition that you're trying to add to your own project that has been recently added to the slim skeleton?

**Comment by Guyverix** [comment]
I had seen updates and changes to the skeleton that looked like they may be useful in my project, and wanted to get any bug fixes that were in place.  I just was not really sure how to get the delta between the really old skeleton that I have been using for the last couple of years and the updates that happened.

There was nothing specific overall that I needed in the latest release, but since I am still quite new at writing PHP code, I wanted to keep the skeleton as updated as possible so I could learn more.  I am trying really hard to not develop bad habits with my code, and I felt that if I followed the skeleton closely that I would have fewer problems.

**Comment by l0gicgate** [comment]
The only way to achieve this with an existing project would be to diff the two and manually incorporate the changes that you like unfortunately. I'm closing this as resolved.
