### ISSUE TITLE
Create a Slim project without the user example

### ISSUE THREAD

**Issue by programarivm** [slimphp/Slim-Skeleton#337]
👋 Hello, 

Is there a way to create a new Slim project without Slim's default Action-Domain-Responder example for managing users?

```
$ composer create-project slim/slim-skeleton [my-app-name]
```

Thank you,

**Comment by l0gicgate** [comment]
There is not unfortunately.

You can checkout other skeletons for Slim 4 like https://github.com/odan/slim4-skeleton or find more on github searching for "Slim 4 Skeleton"
