### ISSUE TITLE
Q: Why logs and templates are out of src?

### ISSUE THREAD

**Issue by mbrig-co** [slimphp/Slim-Skeleton#38]
Just need a brief description about the skeleton specifically why logs and templates more specifically templates are out of src?

**Comment by akrabat** [comment]
`src` contains PHP files,` templates` contains HTML files. `logs` contains log files and in production probably wouldn't be directly with the application.

**Comment by mbrig-co** [comment]
So in that case why to not include templates in public directory?

**Comment by akrabat** [comment]
Files in the `public` directory are accessible by and served by the web server directly. Hence any file in that directly could be served to a browser and we don't want the templates served directly as they need to be processed by PHP.

**Comment by mbrig-co** [comment]
Okay thanks, I understood the concept of these directories.

**Comment by akrabat** [comment]
You're very welcome.
