### ISSUE TITLE
Composer complaines about version

### ISSUE THREAD

**Issue by Hestros** [slimphp/Slim-Skeleton#40]
I ran composer create project slim/slim-skeleton [my-project]
and I got...
 [UnexpectedValueException]                                              
  Could not parse version constraint slim: Invalid version string [my-project]

As a 'good citizen' I follow the instructions by the letter but... 
My guess is, create project  requires a version as second parameter ... hum no tried that... too many arguments!!!
OK I run out of ideas.... Any help?

**Comment by Hestros** [comment]
Sorry stupid typo.... Really sorry 
create project ??? instep create-project , Next time copy-paste

**Comment by akrabat** [comment]
I'm glad you worked it out :)

**Comment by Hestros** [comment]
Yeah I did but still is embarrassing!!!
