### ISSUE TITLE
Slight inconvenience with route pattern matching?

### ISSUE THREAD

**Issue by dwangus** [slimphp/Slim-Skeleton#42]
I don't know if this is an issue with Slim-Skeleton or the Slim framework in general, but I noticed that in src/routes.php, the order in which you write your routes actually matters in some fringe cases.

For example (and this is what happened for me), let's say I have 2 routes:

$app->get('/hours/{name}', ...);
$app->get('/{date}/{name}', ...);

I noticed that if I write the second route in routes.php before the first route, it essentially makes null any calls to the first route -- and in the second route, $args['date'] will always be the string 'hours'.

Is there a way to reinforce, no matter the order routes are written, that certain paths with concrete names get precedence before those with variable argument-names?

**Comment by silentworks** [comment]
Unfortunately there is no way to reinforce this other than the order you write them in. This is the same for all PHP Frameworks, essentially the second route would act as a wildcard and capture all args including the word `hours` hence why it wouldn't get to the first route if the order is changed.

**Comment by RhanCandia** [comment]
@dwangus Maybe if you explicitly declare a pattern like so:

$app->get('/hours/{name}', ...);
$app->get('/{date:[date-format-regex]}/{name}', ...);

So that the second one know that he shouldn't catch the above route.

**Comment by akrabat** [comment]
This is an effect of using FastRoute.
