### ISSUE TITLE
Get queries with params

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim-Skeleton#46]
Inn baseTestCase is request data handling:

```
if (isset($requestData)) {
            $request = $request->withParsedBody($requestData);
        }
```

But shouldn't You use `$request->withQueryParams($requestData)` in `GET` method?

**Comment by casmith** [comment]
I believe that would be true if working with GET requests, but I think the intention of `$requestData` is for setting the request body of POST requests. The first argument to the function is `requestMethod` which is not necessarily GET.
