### ISSUE TITLE
BaseTestCase doesn't implement $_SESSION properly

### ISSUE THREAD

**Issue by kevinburke** [slimphp/Slim-Skeleton#50]
See the details of this bug: https://github.com/slimphp/Slim-Flash/issues/27

Is it possible the test runner should be doing something differently?

**Comment by kevinburke** [comment]
I solved this by adding `$_SESSION = array();` before loading dependencies.php

**Comment by l0gicgate** [comment]
This has been fixed in the recent Slim 4 release version

**Comment by SimonDevelop** [comment]
Hi, I have the similare problem with slim 4 and csrf middleware:
```
RuntimeException: Invalid CSRF storage. Use session_start() before instantiating the Guard middleware or provide array storage.
```
An idea of how to handle this?
I do not use session middleware in the example of skeleton slim 4, does that solve the problem?

**Comment by l0gicgate** [comment]
@SimonDevelop you need to either use session middleware that will run before the CSRF middleware runs or call `session_start()` manually before you instantiate the CSRF middleware

**Comment by SimonDevelop** [comment]
Yes but I have this problem only for my tests with phpunit.
I tested with a middleware and manually before but it does not change anything.

**Comment by SimonDevelop** [comment]
Ok, after several tests I ended up understanding how to do it.
I have to do the session_start () in my bootstrap.php file before it calls the autoload of composer.

With slim 3, start the session before the container was enough.
