### ISSUE TITLE
manully add to existing project

### ISSUE THREAD

**Issue by redimongo** [slimphp/Slim-Skeleton#58]
Hi I am wondering how I can add this to a composer.json that I have already ran and don't want to have to start all over again.

This is what my composer .json looks like

```
{
    "require": {
       "google/cloud":"0.2.*",
	      "mongodb/mongodb":"1.0.*"
    }
}

```

**Comment by lferro9000** [comment]
To manually add to an existing project, it's probably adviseable to use the base Slim Framework only. Use the skeleton on a side folder to use as a guidance on how to configure it only.

The skeleton is built around composer scripts that run after the dependencies are setup to add things like the whole folder structure (apart from the target folder and it's corresponding vendor one).

**Comment by akrabat** [comment]
As @lferro9000 says, use the Skeleton as inspiration and use `composer require {package name}` to add the Slim component(s) that you want.
