### ISSUE TITLE
How to integrate right way in to Slim?

### ISSUE THREAD

**Issue by RopoMen** [slimphp/Slim-Skeleton#63]
Hi,

I have used Slim3 now for a week and a half. My application is very simple and it has cli access through slim-cli. What I currently have noticed is that my own custom php classes are not using Slim almost at all, for example I would like to use logger/settings defined in Slim (in dependencies.php) in my own classes, but how do I do that?

Referencing this: https://github.com/slimphp/Slim/issues/1722

Since you removed Slim::getInstance(), your current slim-skeleton app does not show up any example how you get handle to your slim app in your own custom classes.

Could you provide simple examples from that in your skeleton app?

Br,
-Markku

**Comment by RopoMen** [comment]
My initial thoughts have been like "I keep handle to $app and each time I construct any of my own php classes, I pass $app in to constuctor"

``` 
$instance = new \My\Custom\Class($app);
```

but this does not look good....

**Comment by akrabat** [comment]
Pass the logger into the constructor of your classes via Dependency Injection.

e.g. https://github.com/akrabat/slim-bookshelf-api/blob/master/api/src/Bookshelf/AuthorMapper.php#L11

**Comment by akrabat** [comment]
Also, this question is best asked on discourse.slimframework.com
