### ISSUE TITLE
Are pull requests being looked at?

### ISSUE THREAD

**Issue by AntonioCS** [slimphp/Slim-Skeleton#64]
Hey,

I have been using the slim for some recent projects and I would like to contribute but I see pull requests from last year that haven't been rejected or accepted.

Is anyone doing any review on the pull requests?

**Comment by akrabat** [comment]
Very slowly to be honest. I'm hopeful that the pace will pick up from next month though.

**Comment by AntonioCS** [comment]
Ok, thanks for letting me know.
