### ISSUE TITLE
BaseTestCase should store app as local property

### ISSUE THREAD

**Issue by ChangePlaces** [slimphp/Slim-Skeleton#68]
I think the initialisation of `$app` should be stored into a protected variable so setup / teardown methods can operate on it or access the container where necessary. e.g. I'm currently using the setup and teardown methods to begin a transaction and rollback at the end of the test respectively to prevent the tests from affecting my test database. I'm setting up the app in the setup method.

I've also added a little helper method for the functional test basetestcase called `getResponseBody` to simple get the body content of the response as a string such `return $response->getBody()->__toString()`. Is there a simpler way to get access to the response body as a string? If not, this would make a nice addition to the BaseTestCase.

**Comment by lferro9000** [comment]
If the tests affect the database, then the best solution would be probably to ensure that the database is setup and reset on the setup / tear down. It is not the responsability of the app or the test modules to ensure that.

**Comment by akrabat** [comment]
The tests are mainly there to inspire you. You should adapt them as you feel best enables you to test your application.
