### ISSUE TITLE
what does the container callback params mean in dependencies.php?

### ISSUE THREAD

**Issue by shanezhiu** [slimphp/Slim-Skeleton#75]
Hi,I am new fish about slim, I cloned the Slim-Skeleton to my computer,and it works fine.But when I check the code,I am confused about the
```
 $container['renderer'] = function ($c) {
    $settings = $c->get('settings')['renderer'];
    return new Slim\Views\PhpRenderer($settings['template_path']);
};
``` 

in the `dependencies.php` ? what does the  param $c mean?

**Comment by uighurbabbage** [comment]
when new a slim -> this is my  code : 
```
 $this->slim_app = new App($this->gloablConfigs);
        //默认绑定容器
        $slim_containers = $this->slim_app->getContainer();
```

this is my conde in the dependencies.php:
```
$container = $app->getSlimApp()->getContainer();

// view renderer
$container['renderer'] = function ($c) {
    $settings = $c->get('settings')['renderer'];
    return new Slim\Views\PhpRenderer($settings['template_path']);
};

// monolog
$container['logger'] = function ($c) {
    $settings = $c->get('settings')['logger'];
    $logger = new Monolog\Logger($settings['name']);
    $logger->pushProcessor(new Monolog\Processor\UidProcessor());
    $logger->pushHandler(new Monolog\Handler\StreamHandler($settings['path'], $settings['level']));
    return $logger;
};
```
and  you  follow new Slim()->getContainer() ,you can find that it is the default container holding all services the slim provide 
  so you can understand that  $c params  is the  all thing Slim have
My English is not good. I hope this will help you

**Comment by shanezhiu** [comment]
and I have tried to  watch it by debug, but it does not show anything useful information.
this is my test.

![image](https://user-images.githubusercontent.com/5237302/32586541-106c5168-c53e-11e7-9fae-cde70caa8dda.png)

**Comment by uighurbabbage** [comment]
you can write this code in the dependencies.php:
`  dump($container);die();`
the information maybe help you understand more thing about it .
I suggest you keep track with  `$slim_app->getContainer()`

**Comment by uighurbabbage** [comment]
I refer to the Laravel Frame work and Thinkphp frame work 
Transform the  Slim-Skeleton into a new architecture  
If you're interested, I'll give  the code  by email

**Comment by shanezhiu** [comment]
I could not get your words. Do you mean that the `$c` point to the `$this->app` or the `container` itself?

**Comment by uighurbabbage** [comment]
all thing is Depends on the container in slim ,and $c is the core Container that provide all services the slim defaul had

**Comment by uighurbabbage** [comment]
With a translator, I can't tell you what I want to say. I'm sorry

**Comment by uighurbabbage** [comment]
$c 参数是Slim 框架初始化时就赋有的默认容器。
slim框架里的每一个特殊功能都可以理解为是一个容器。而$c是作为框架默认容器 拥有了框架默认自带的所有功能服务在里面。可以理解为我们所有东西都在这个container上

**Comment by shanezhiu** [comment]
Thanks,do you mean that the `$c` refers to  the array composed of default services provided by the `Slim Framework`?

**Comment by uighurbabbage** [comment]
yes  yes     that is right [Thanks,do you mean that the $c refers to the array composed of default services provided by the Slim Framework]

**Comment by shanezhiu** [comment]
Thanks for your help!,I got it !

谢谢你的帮助，我明白了。

**Comment by uighurbabbage** [comment]
我还以为.... 哈哈 原来你会中文嘛这是  。
早知道我直接用中文给你解析。哈哈哈

**Comment by shanezhiu** [comment]
You had better not to do that. This question will be seen by those who did not speak Chinese after all.

还是别那么做了，这个问题是面向很多人的，我们要为那些不会中文的人考虑，同时，如果参与问题的人越多，我们得到的也就越多。

**Comment by uighurbabbage** [comment]
yes  you are right.
maybe others  use translator get more and right information by Chinese explanation （smile）
