### ISSUE TITLE
Can't generate code coverage report with phpunit

### ISSUE THREAD

**Issue by joostdecock** [slimphp/Slim-Skeleton#77]
Out of the box, the unit tests in this skeleton are a good starting point as such, but it's not possible to generate a code coverage report:

```
phpunit --coverage-text
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.

Undefined variable: app
```

Perhaps the way the tests are bootstrapped needs to be altered for this?

Either way, the coverage report is a great help for people who want to build comprehensive tests, so it would be handy if that could work out of the box too.

**Comment by akrabat** [comment]
The `phpunit.xml` doesn't have a whitelist.

You need to add:

```
    <filter>
        <whitelist>
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
```

**Comment by joostdecock** [comment]
Thank you for your feedback. I forgot to mention that I did add the whitelist.

But regardless, this issue seems to have been related to my environment, because now on a fresh install it works fine.

Please forgive me while I go eat humble pie.
