### ISSUE TITLE
Issue with creating the container.

### ISSUE THREAD

**Issue by milpas999** [slimphp/Slim-Skeleton#78]
I am trying to create a service for the database connection. I have used the same steps as given in the slim 3 and pimple DI documentation. But Container is not getting created.

```php
$container['dbMeedo'] = function($c) {
    $arrDriverDetails = $settings = $c->get('settings')['dbMeedo'];
    $MedooDb = new Medoo($arrDriverDetails);
    return $MedooDb;
};
```

**Comment by geggleto** [comment]
that is not how you construct a container; that is how you define a service in the container.

**Comment by nhymxu** [comment]
try

```php
$db = 
$container['dbMeedo'] = function($c) {
    $arrDriverDetails = $c['settings']['dbMeedo'];
    $MedooDb = new Medoo($arrDriverDetails);
    return $MedooDb;
};
```

**Comment by akrabat** [comment]
Are you doing `$container = $app->getContainer()` ?

**Comment by jimmy18dev** [comment]
`
$container = $app->getContainer();

// view renderer
$container['renderer'] = function ($c) {
    $settings = $c->get('settings')['renderer'];
    return new Slim\Views\PhpRenderer($settings['template_path']);
};
`

**Comment by akrabat** [comment]
@milpas999 Have you resolved your issue?

**Comment by l0gicgate** [comment]
This issue is stale. Closing.
