### ISSUE TITLE
docker-compose, the container is given php errors

### ISSUE THREAD

**Issue by leroy0211** [slimphp/Slim-Skeleton#79]
When starting the skeleton with docker-compose, some errors occur. 

The error you get in the browser is: 
```
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required '/var/www/public/public/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0
```

After some time, I saw that there is `/public/public/` in the folder name. Then I looked in the docker-compse file. The document root is set to `public`, but it tries to start `public/index.php` which is duplicate.

**Comment by leroy0211** [comment]
Update: 
I see that there's already a PR #76 .

**Comment by silentworks** [comment]
This PR has now been merged. Will create a new release soon.
