### ISSUE TITLE
Access-Control-Allow-Origin Cors header problem

### ISSUE THREAD

**Issue by davparcar** [slimphp/Slim-Skeleton#83]
Hi all,

i'm using angular 5 and slim 3.1 for my app.

I'm trying to change Access-Control-Allow-Origin * to my domain but i can't.
Other headers change successfuly, but Origin its allways *.

I follow the main page for this:
https://www.slimframework.com/docs/cookbook/enable-cors.html

what its wrong with this? its a bug?

thanks

**Comment by akrabat** [comment]
Please provide a single file app that shows the problem.

**Comment by davparcar** [comment]
it was a problem from my ngix server.
i test the same code in other server and works correctly everything, so isn't slim bug.

thanks for all.
