### ISSUE TITLE
Docker Compose Bug?

### ISSUE THREAD

**Issue by svpernova09** [slimphp/Slim-Skeleton#84]
in `docker-compose.yml` the line:

```
command: php -S 0.0.0.0:8080 -t public index.php
```

Was throwing errors for me:

```
bash-3.2$ docker-compose up
Recreating myfirstslimphpapp_slim_1 ...
Recreating myfirstslimphpapp_slim_1 ... done
Attaching to myfirstslimphpapp_slim_1
slim_1  | PHP 7.2.2 Development Server started at Thu Feb  8 17:13:57 2018
```

<img width="832" alt="screen shot 2018-02-08 at 12 14 27" src="https://user-images.githubusercontent.com/967362/35987432-a2197442-0cc9-11e8-984d-94b92bc6a001.png">

I had to change it to:

```
command: php -S 0.0.0.0:8080 -t public
```

```
bash-3.2$ docker-compose up
Recreating myfirstslimphpapp_slim_1 ...
Recreating myfirstslimphpapp_slim_1 ... done
Attaching to myfirstslimphpapp_slim_1
slim_1  | PHP 7.2.2 Development Server started at Thu Feb  8 17:14:53 2018
```

<img width="774" alt="screen shot 2018-02-08 at 12 15 32" src="https://user-images.githubusercontent.com/967362/35987484-c7cbf0b6-0cc9-11e8-8416-c40d49a53870.png">

Am I doing something wrong or is this a bug that should be fixed in the project?

**Comment by silentworks** [comment]
@svpernova09 that is weird, I just tested this and its working as expected. Can you give me a bit more information please, which OS? and what version of Docker?

**Comment by svpernova09** [comment]
MacOS 10.13.3

Docker:

<img width="578" alt="screen shot 2018-02-08 at 13 04 59" src="https://user-images.githubusercontent.com/967362/35990014-c1cc396c-0cd0-11e8-85c7-ed6a4b396ffd.png">

If it's just me, no big deal. Just wanted to check if it was a bug or not.

**Comment by silentworks** [comment]
My OS is the same as yours, I am 1 version ahead with Docker, but I just upgraded now, I was probably on the same version as you before. Its working fine here, hey @geggleto can you test this on your machine please.

**Comment by geggleto** [comment]
yap

**Comment by geggleto** [comment]
<img width="884" alt="screen shot 2018-02-08 at 1 23 32 pm" src="https://user-images.githubusercontent.com/4027602/35990826-50a4b360-0cd3-11e8-8cb9-54aa51d6248f.png">

Repoducable steps.

1. git clone repo
2. docker-compose up
3. localhost:8080

**Comment by geggleto** [comment]
I can confirm that the update to docker-compose.yml that joe made fixes it.

**Comment by svpernova09** [comment]
After talking this over with @akrabat I changed the line to this:

```
command: php -S 0.0.0.0:8080 -t public public/index.php
```

And it works as you'd expect. I'm happy to open a PR but feel that removing `index.php` is the better fix if it doesn't break things for you @silentworks and I'll open PR once we confirm.

Thanks

**Comment by silentworks** [comment]
I can confirm that changing it back to that will break it for some users. That was the original setup. We can however try out your newly suggested command.

```
command: php -S 0.0.0.0:8080 -t public
```
