### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by droidwithme** [slimphp/Slim-Skeleton#90]
I have setup as described in this tutorial, but still i am getting No input file specified when i try hit this url
http://aami.noqplz.com/App/public/Hello 
the above url shows 

**Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator and inform them of the time the error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.**

but this 
http://aami.noqplz.com/App/public/ Url working fine.

and this url 
http://aami.noqplz.com/App/public/index.php/Hello/Devendra
Shows No input file specified.
Please help me. i am in problem.

**Comment by tflight** [comment]
As the message says, more details about the  error should be in your webserver's error log. 😀

**Comment by droidwithme** [comment]
[2018-04-06 12:27:20] slim-app.INFO: Slim-Skeleton '/' route [] {"uid":"6d87659"}
[2018-04-06 12:50:38] slim-app.INFO: App-AAMI '/' route [] {"uid":"9e1593e"}

**Comment by tflight** [comment]
Is that the webserver's error log, or your app's app.log? If you `echo ini_get('error_log')` I believe that will tell you the location of the webserver's error log.

**Comment by droidwithme** [comment]
This project running locally but not on live server.

**Comment by tflight** [comment]
Often, but not always the reason that happens is the environments are not a perfect match (different PHP version, etc). But you will need to find the error log and see what it says about the error.

**Comment by droidwithme** [comment]
if the php version is differ then how this url is working
http://aami.noqplz.com/App/public/

**Comment by droidwithme** [comment]
Should i put php.ini in project root folder? or .htaccess file in root folder?

**Comment by tflight** [comment]
Different code. Some might work with both versions, some might not. But again, look in the error log as that will tell you what is going on.
