### ISSUE TITLE
Not working on nginx 

### ISSUE THREAD

**Issue by newbie14** [slimphp/Slim-Skeleton#95]
Hi,
   I have created via the composer a folder. Then I add this settings for nginx 

location /apitest {
        try_files $uri /public/index.php$is_args$args;
        }
but its working either. So how to settle this issue ?

**Comment by muhaimincs** [comment]
can you reveal more how do you structure your project

**Comment by l0gicgate** [comment]
Closing this as stale, feel free to re-open with more feedback.
